import org.springframework.beans.factory.annotation.QualifierAnnotationAutowireCandidateResolver;
public class FunctionUse1692 {
public void funcUse() {
QualifierAnnotationAutowireCandidateResolver qualifierannotationautowirecandidateresolver = new QualifierAnnotationAutowireCandidateResolver();
qualifierannotationautowirecandidateresolver.addQualifierType(null);
}
}