import org.springframework.beans.factory.annotation.QualifierAnnotationAutowireCandidateResolver;
public class FunctionUse1686 {
public void funcUse() {
QualifierAnnotationAutowireCandidateResolver qualifierannotationautowirecandidateresolver = new QualifierAnnotationAutowireCandidateResolver();
qualifierannotationautowirecandidateresolver.getQualifiedElementAnnotation(null,null);
}
}