import org.springframework.beans.factory.annotation.QualifierAnnotationAutowireCandidateResolver;
public class FunctionUse1685 {
public void funcUse() {
QualifierAnnotationAutowireCandidateResolver qualifierannotationautowirecandidateresolver = new QualifierAnnotationAutowireCandidateResolver();
qualifierannotationautowirecandidateresolver.getSuggestedValue(null);
}
}